version: "3.9"

services:
  sentinel-postgres:
    image: postgres:15
    container_name: sentinel-postgres
    restart: always
    environment:
      POSTGRES_USER: sentinel
      POSTGRES_PASSWORD: sentinelpass
      POSTGRES_DB: sentinel_db
    ports:
      - "5432:5432"
    volumes:
      - sentinel_pgdata:/var/lib/postgresql/data

volumes:
  sentinel_pgdata: